import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "./config";
import { ENGINE_DIR } from "./paths";
import { log } from "./log";

// Generate engine/mozconfig for direct mach builds (mach build / mach build
// faster / mach configure when invoked outside `nix build`).
//
// `nix build .#gjoa` does NOT use this file — buildMozillaMach generates
// its own configure flags inside the sandbox. This mozconfig only matters
// for the incremental dev loop where you run mach directly against engine/.
//
// We expand $LIBCLANG_PATH at file-write time rather than relying on mach
// to pick up the env var, because mach's configure subprocess doesn't
// always inherit env vars cleanly through its virtualenv layers.
export async function mozconfig(): Promise<void> {
  const cfg = loadConfig();
  const libclang = process.env.LIBCLANG_PATH;
  if (!libclang) {
    log.warn(
      "LIBCLANG_PATH not set — engine/mozconfig will not include " +
      "--with-libclang-path. Run prep from inside `nix develop` so the " +
      "dev shell sets it.",
    );
  }

  const lines = [
    "# AUTOGENERATED by tools/prep — do not edit by hand.",
    "# Used only for direct mach builds (cd engine && ./mach build [faster]).",
    "# `nix build .#gjoa` ignores this and uses buildMozillaMach's flags.",
    "",
    `ac_add_options --with-branding=browser/branding/${cfg.binaryName}`,
    `ac_add_options --with-distribution-id=org.${cfg.binaryName}`,
    `ac_add_options --with-app-name=${cfg.binaryName}`,
    `ac_add_options --with-app-basename=${cfg.branding.shortName}`,
    "",
    "# Skip wasm-sandboxed libraries (would need wasi-sysroot we don't ship).",
    "ac_add_options --without-wasm-sandboxed-libraries",
    "",
    "# Dev-loop ergonomics.",
    "ac_add_options --disable-updater",
    "ac_add_options --disable-tests",
    "ac_add_options --enable-optimize",
    "ac_add_options --enable-release",
    "",
    "# Use clang from dev shell.",
    "export CC=clang",
    "export CXX=clang++",
    "export AS=clang",
    "",
  ];

  if (libclang) {
    lines.splice(
      4,
      0,
      `ac_add_options --with-libclang-path="${libclang}"`,
      "",
    );
  }

  const path = join(ENGINE_DIR, "mozconfig");
  if (!existsSync(ENGINE_DIR)) {
    throw new Error(`engine/ does not exist — run \`bun run download\` first`);
  }
  await writeFile(path, lines.join("\n"));
  log.ok(`wrote engine/mozconfig${libclang ? "" : " (without libclang path — set LIBCLANG_PATH and re-run)"}`);
}
